### ISSUE TITLE
Audio controller adjusts all active sound volumes when only one sound mix type is changed

### ISSUE THREAD

**Issue by stanleyqubit** [MWSE/MWSE#415]
**Describe the Bug**
Kind of two bugs, actually. One, setting the volume to a particular sound mix type via the `audioController` is causing ALL active sounds to be reset to their respective volume slider in Audio settings, even if they aren't currently playing at this volume - this is the 2nd bug, where the game engine doesn't respect slider volumes on fresh load or after a cell change. Not until you start moving the audio sliders.

**To Reproduce**
1. Go to Options - Audio and set Master and Effects to max volume
2. Open the console and `coc "arkngthand, hall of centrifuge"` (bug not necessarily tied to this cell, this is just an example where some looping sound effects can be heard properly)
3. Go to Options - Audio and click on the left arrow on the Effects or Master slider as to decrease the volume by 1%

**Expected Behavior**
Active sounds volume decreases by 1%

**Actual Behavior**
Active sounds volume reset from a much lower value to the current slider value

**Additional Context**
Now the strange thing is that this only applies if you're trying to change either Effects or Master volumes if you're using the Options-Audio UI. But if you're trying to set ANY of the sound mix types volumes via `tes3.worldController.audioController` you'll get the same behavior.

This for instance breaks mods that play looping sounds on `tes3.soundMix.effects` with a volume lower than 1, when another mod is using the `audioController` to set a new value to say, `volumeVoice`. It would be expected that setting `volumeVoice` doesn't affect active sounds playing on `tes3.soundMix.effects`.

**Comment by Hrnchamd** [comment]
Please update MWSE and test. Hopefully both bugs are fixed now.

The engine bug was due to sound mix volume updates using an incorrect volume calculation for cloned sound buffers. It only considered the mix volumes, but didn't use the volume in the sound effect record. After changing a volume slider, that would result in louder audio for any sound effect that wasn't set to max volume.

**Comment by stanleyqubit** [comment]
@Hrnchamd Thanks, updated. However, the issue still persists, but in a different way. If I have the Master slider set to max and then try to move the Effects slider to the left, I get no issues. But if I move the Effects slider all the way to the right, then some (not all) of the sounds effects will get louder. There's a big jump in volume when the slider reaches the right hand side (max) limit, and also some strange sound artifacts appear like I can hear 2 sound effects play at the same time with a slight delay between them.

But if I have the Master volume slider set to a value lower than than the max, this issue no longer occurs. Hmm...

Upon further investigations, I get these results when I monitor `tes3.event.soundObjectPlay`:

```
[onSoundObjectPlay] e.sound.id: Steam
[onSoundObjectPlay] e.volume: 125
[onSoundObjectPlay] e.sound.volume: 0.71200001239777
[onSoundObjectPlay] e.sound.id: Power Light
[onSoundObjectPlay] e.volume: 125
[onSoundObjectPlay] e.sound.volume: 0.81599998474121
[onSoundObjectPlay] e.sound.id: Ambient Factory Ruins
[onSoundObjectPlay] e.volume: 250
[onSoundObjectPlay] e.sound.volume: 1.0199999809265
[onSoundObjectPlay] e.sound.id: Cave Wind
[onSoundObjectPlay] e.volume: 250
[onSoundObjectPlay] e.sound.volume: 0.81599998474121
```

(this is right after I `coc "arkngthand, hall of centrifuge"`)

Notice how the event data for "Ambient Factory Ruins" has a `sound.volume` of `1.0199999809265`, which is a bit peculiar, not sure why it returns a value greater than 1. So, that is the only sound effect in that cell that I experience this issue with. But it seems that all sound objects with a `volume` greater than 1 (e.g. as returned by `tes3.getSound`), are subject to this issue. There are no problems with sound objects whose `volume` property is anything lower than 1. I'm talking strictly about vanilla sound objects.

**Comment by stanleyqubit** [comment]
Bit more context. So the first steps to test current issue are:
1. Go to Options - Audio and set Master and Effects volumes to max
2. `coc "arkngthand, hall of centrifuge"`

Now open the lua console:

```
tes3.worldController.audioController.volumeMaster
> 1 (as expected)
tes3.worldController.audioController.volumeMaster = 1
(bug occurs)
tes3.getSound("Ambient Factory Ruins").volume
> 1.0199999809265 (culprit)
```

The "Ambient Factory Ruins" sound object gets significantly louder, and you can hear how there are now 2 instances of the same sound playing at the same time.


Bug no longer occurs if I set "Ambient Factory Ruins" volume to something less or equal than 1 and then reset the Master volume in order to adjust active looping sounds:

```
s = tes3.getSound("Ambient Factory Ruins")
s.volume
> 1.0199999809265 (bad)
s.volume = 1
s.volume
> 1 (good)
tes3.worldController.audioController.volumeMaster
> 1 (as expected)
tes3.worldController.audioController.volumeMaster = 1
(now all good)
```

**Comment by Hrnchamd** [comment]
There's a new fix posted. It's not perfect, because the engine doesn't always save enough information to set the volume correctly.

- Patched enough of the audio to make "Ambient Factory Ruins" have a consistent volume.
- We had the sound volume scaling slightly wrong, now maximum sound volume should appear as 1.0. The vanilla code was inconsistent, and we picked the wrong scaling factor.
- There is still a remaining issue with sounds scripted via PlaySound3DVP (e.g. "Steam"). The script command has a volume parameter that applies on top of the other volume settings. All the volume settings are collapsed to a final volume. Not enough information is stored to update the master/effects mix independently for scripted sounds.

**Comment by stanleyqubit** [comment]
Awesome, that fixed most of it. And I like that sounds now immediately react to having their `volume` property changed directly. However,

```
s = tes3.getSound("Ambient Factory Ruins")
s.volume
> 1 (good)
s.volume = 1
(sound gets louder)
s.volume = 1
(sound gets incredibly quiet)
tes3.worldController.audioController.volumeMaster = 1
(now back to normal)
```

Seems that looping sounds volume needs to be adjusted every time the sound object's `volume` gets changed. Unless I'm seeing things wrong, it would be expected that this was done automatically.

Also related, during rain:

```
s = tes3.worldController.weatherController.currentWeather.rainLoopSound
tes3.getSoundPlaying({sound = s})
> false (hmm...)
s:isPlaying()
> true (as expected)
s.volume
> 1
s.volume = 1
(appears to be getting louder)
s.volume = 1
(gets incredibly quiet)
tes3.worldController.audioController.volumeMaster = 1
(nothing happens, it stays quiet)
(close the console)
(only now back to it playing correctly)
```

**Comment by Hrnchamd** [comment]
Setting tes3sound.volume should work reliably now.

**Comment by stanleyqubit** [comment]
All solved, much appreciated.
